    ("Chainsaw", "No Love Lost", "Passive"),
    ("Chainsaw", "Revved Up", "Passive"),
    ("Chainsaw", "The Carvers Art", "Active"),
    ("Chainsaw", "Timber", "Active"),
    ("Flamethrower", "Assiduous Burn", "Passive"),
    ("Flamethrower", "Cremate", "Active"),
    ("Flamethrower", "Dragons Breath", "Active"),
    ("Flamethrower", "Fire It Up", "Active"),
    ("Flamethrower", "Scorched Earth", "Active"),
    ("Flamethrower", "Searing Magnesium", "Passive"),
    ("Flamethrower", "Smells Like Victory", "Active"),
    ("Flamethrower", "Viscous Accelerant", "Passive"),
    ("Quantum Brace", "Charge Density", "Active"),
    ("Quantum Brace", "Collider Collapse", "Active"),
    ("Quantum Brace", "Energy Transfer", "Passive"),
