const tswData = [
  {
    "tree": "Pistol",
    "name": "Hair Trigger",
    "scaling": 0.16093,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "4 hits, focus",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Channelled: Every 0.25 seconds for 1 second. Builds 1 resource for each equipped weapon. A channelled Focus attack that deals 12 physical damage per hit",
    "type": "",
    "weapon": "Pistol"
  },
  {
    "tree": "Pistol",
    "name": "The Business",
    "scaling": 0.21458,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "3 hits",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Builds 1 resource for each equipped weapon. A single target attack that hits 3 times, dealing 16 physical damage per hit.",
    "type": "Active - Builder",
    "weapon": "Pistol"
  },
  {
    "tree": "Pistol",
    "name": "Big 45",
    "scaling": 0.0,
    "scaling_1": 1.75339,
    "scaling_5": 3.02498,
    "note": "",
    "cast_time": 1.5,
    "cooldown": 4.0,
    "description": "Consumes all Pistol Resources. A single target attack that deals 133 - 229 physical damage, based on the number of resources consumed.",
    "type": "",
    "weapon": "Pistol"
  },
  {
    "tree": "Pistol",
    "name": "Shootout",
    "scaling": 0.0,
    "scaling_1": 0.54241,
    "scaling_5": 0.81461,
    "note": "5 hits, focus, 2.5s",
    "cast_time": 2.5,
    "cooldown": 4.0,
    "description": "Channelled: Every 0.5 seconds for 2.5 seconds. Consumes all Pistol Resources. A channelled Focus attack that deals 41 - 62 physical damage per hit, based on the number of resources consumed.",
    "type": "",
    "weapon": "Pistol"
  },
  {
    "tree": "Pistol",
    "name": "Dirty Tricks",
    "scaling": 4.60022,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "AD, hindered",
    "cast_time": 1.0,
    "cooldown": 25.0,
    "description": "GTAoE: Affects up to 6 enemies in a 5 metre radius around the targeted point. A GTAoE attack that deals 348 physical damage. Affected targets become Hindered and rooted to the ground for 4 seconds. Targets also become Weakened by 5 stacks of the Corrupted effect, which reduces the effectiveness of heal, barrier and leech effects by 5% per stack for 10 seconds. This effect can stack up to 10 times. Susceptible to Anima Deviation.",
    "type": "Active - Elite",
    "weapon": "Pistol"
  },
  {
    "tree": "Pistol",
    "name": "Collaboration",
    "scaling": 0.61647,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Builds 1 resource for each equipped weapon. A single target attack that deals 47 physical damage. Cleanses you of 1 detrimental effect. This effect has an internal recharge time of 5 seconds.",
    "type": "",
    "weapon": "Pistol"
  },
  {
    "tree": "Pistol",
    "name": "Bond, Strong Bond",
    "scaling": 0.0,
    "scaling_1": 0.23924,
    "scaling_5": 0.3812,
    "note": "10 hits, 3s",
    "cast_time": 3.0,
    "cooldown": 4.0,
    "description": "Channelled: Every 0.3 seconds for 3 seconds. Consumers all Pistol Resources. A channelled attack that deals 18 - 29 physical damage, based on the number of resources consumed. At the end of the channel, cleanses 1 detrimental effect from up to 5 allies within 5 metres of you.",
    "type": "",
    "weapon": "Pistol"
  },
  {
    "tree": "Pistol",
    "name": "Area Drone",
    "scaling": 0.46757,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "5 times, 5s",
    "cast_time": 1.0,
    "cooldown": 4.0,
    "description": "Consumes all Pistol Resources. Summons a drone that will follow you around for 5 seconds. Every seconds it will attack up to 6 enemies around the target, dealing 16 - 31 physical damage, or 18 - 35 physical damage to targets that are Weakened. If the target dies before the drone is finished attacking it will deal 39 - 77 physical damage to targets within the same area. Damage scales based on the number of resources consumed.",
    "type": "",
    "weapon": "Pistol"
  },
  {
    "tree": "Pistol",
    "name": "Bullet Ballet",
    "scaling": 0.57974,
    "scaling_1": 0.27597,
    "scaling_5": 1.44836,
    "note": "10 hits, 2s, MELEE; final hit; final hit",
    "cast_time": 2.0,
    "cooldown": 20.0,
    "description": "Channelled: Every 0.2 seconds for 2 seconds. PBAoE: Affects up to 6 enemies in a 10 metre radius around you. Consumes all Pistol Resources. A channelled PBAoE attack 44 physical damage per hit. If you have pistol resources on a target the final hit of this attack deals an additional 21 - 110 physical damage to targets, based on the number of resources consumed. Also, whenever you hit, you gain a single stack of Critical Rating effect, which increases your Critical Rating by 40 per stack for 8 seconds. This effect can stack up to 5 times. While channelling you are rooted to the ground. Applies Vulnerable to Melee.",
    "type": "Active - Elite",
    "weapon": "Pistol"
  },
  {
    "tree": "Pistol",
    "name": "Marked",
    "scaling": 2.17304,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "1.5s",
    "cast_time": 1.5,
    "cooldown": 30.0,
    "description": "A single target attack that deals 165 physical damage. The target becomes Weakened by 5 stacks of Corrupted effect, which reduces the effectiveness of heal, barrier and leech effects by 5% per stack for 10 seconds. This effect can stack up to 10 times.",
    "type": "",
    "weapon": "Pistol"
  },
  {
    "tree": "Pistol",
    "name": "Start & Finish 1st",
    "scaling": 0.30278,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "1st hit"
  },
  {
    "tree": "Pistol",
    "name": "Start & Finish",
    "scaling": 0.0,
    "scaling_1": 0.92223,
    "scaling_5": 2.00924,
    "note": "2nd hit",
    "cast_time": 1.0,
    "cooldown": 4.0,
    "description": "Consumes all Pistol Resources. A single  target attack that performs 2 hits. The first hit deals 23 physical damage. The second hit deals 63 - 146 physical damage, or 70 - 152 physical damage if the target is Weakened.",
    "type": "",
    "weapon": "Pistol"
  },
  {
    "tree": "Pistol",
    "name": "Gun Crazy 3xA",
    "scaling": 0.27994,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "10 hits, 3s, MAGIC"
  },
  {
    "tree": "Pistol",
    "name": "Gun Crazy 3xB",
    "scaling": 0.46657,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "next 3"
  },
  {
    "tree": "Pistol",
    "name": "Gun Crazy 3xC",
    "scaling": 0.817,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "next 3"
  },
  {
    "tree": "Pistol",
    "name": "Gun Crazy Final",
    "scaling": 2.31103,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "final hit (additional)"
  },
  {
    "tree": "Pistol",
    "name": "One in the Chamber",
    "scaling": 0.3683,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "on crit",
    "cast_time": 0.0,
    "cooldown": 0.0,
    "description": "Whenever you critically hit, you also perform an additional hit dealing 28 physical damage to the target.",
    "type": "Passive",
    "weapon": "Pistol"
  },
  {
    "tree": "Shotgun",
    "name": "Bombardment",
    "scaling": 0.98477,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "every 2.5s for 20s",
    "cast_time": 1.0,
    "cooldown": 30.0,
    "description": "Places a turret at the targeted point. The turret will fire at a random enemy within 7 metres every 2.5 seconds for 20 seconds. Affected enemies are deals 75 physical damage and other enemies within 3 metres are dealt 25 physical damage.",
    "type": "Active - Elite",
    "weapon": "Shotgun"
  },
  {
    "tree": "Shotgun",
    "name": "Takedown",
    "scaling": 1.56166,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "",
    "cast_time": 1.0,
    "cooldown": 25.0,
    "description": "A single target attack that deals 118 physical damage. The target becomes Hindered and its movement speed is reduced by 70% for 4 seconds. If you have 5 Shotgun Resources on the target, the movement reducing effect will last 2 seconds longer.",
    "type": "Active",
    "weapon": "Shotgun"
  },
  {
    "tree": "Shotgun",
    "name": "Striker",
    "scaling": 0.64374,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "strike",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Builds 1 resource for each equipped weapon. A single target Strike attack that deals 49 physical damage.",
    "type": "Active - Builder",
    "weapon": "Shotgun"
  },
  {
    "tree": "Shotgun",
    "name": "Single Barrel",
    "scaling": 0.6805,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "",
    "cast_time": 0.5,
    "cooldown": 0.0,
    "description": "Builds 1 resource for each equipped weapon. A single target attack that deals 47 physical damage, or 52 physical damage if the target is Weakened.",
    "type": "Active - Builder",
    "weapon": "Shotgun"
  },
  {
    "tree": "Shotgun",
    "name": "Out for a Kill",
    "scaling": 0.0,
    "scaling_1": 1.19608,
    "scaling_5": 2.36832,
    "note": "",
    "cast_time": 1.0,
    "cooldown": 4.0,
    "description": "Consumes all Shotgun Resources. A single target attack that deals 91 - 179 physical damage, based on the number of resources consumed. Enermies who are killed shortly after being hit will grant you a beneficial effect for 8 seconds which increases the Penetration Chance of your attacks from manifestations, turrets, mines or drones by 10%",
    "type": "Active - Consumer",
    "weapon": "Shotgun"
  },
  {
    "tree": "Shotgun",
    "name": "Sure Shot",
    "scaling": 0.0,
    "scaling_1": 1.19608,
    "scaling_5": 2.36832,
    "note": "",
    "cast_time": 1.0,
    "cooldown": 4.0,
    "description": "Consumes all Shotgun Resources. A single target attack that deals 91 - 179 physical damage, based on the number of resources consumed. If the target is Hindered, you also cleanse 1 detrimental effect from your defensice target and purge 1 beneficial effect from the target.",
    "type": "Active - Consumer",
    "weapon": "Shotgun"
  },
  {
    "tree": "Shotgun",
    "name": "Powder Burn",
    "scaling": 0.64427,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "strike",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Builds 1 resource for each equipped weapon. A single target Strike attack that deals 49 physical damage, or 56 physical damage if the target is Hindered",
    "type": "Active - Builder",
    "weapon": "Shotgun"
  },
  {
    "tree": "Shotgun",
    "name": "Kneecapper",
    "scaling": 4.60022,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "AD, hindered",
    "cast_time": 1.0,
    "cooldown": 25.0,
    "description": "Cone: Affects up to 10 enemies in a 60 degree 9 metre cone in front of you. A cone attack that deals 348 physical damage. Affected targets also become Hindered and their movement speed is reduced by 70% for 8 seconds.",
    "type": "Active - Elite",
    "weapon": "Shotgun"
  },
  {
    "tree": "Shotgun",
    "name": "Shotgun Turret",
    "scaling": 0.0,
    "scaling_1": 0.18762,
    "scaling_5": 0.37227,
    "note": "once per sec, 5s, blast",
    "cast_time": 1.0,
    "cooldown": 10.0,
    "description": "Consumes all Shotgun Resources. A Blast attack that places a turret at your feet. The turret will fire every seconds for 5 seconds, affecting up to 6 enemies in a 7 metre long 120 degree cone in front of you, dealing 14 - 28 physical damage, based on the number of resources consumed. This ability has a 7 metre range.",
    "type": "Active - Consumer",
    "weapon": "Shotgun"
  },
  {
    "tree": "Shotgun",
    "name": "Point Blank",
    "scaling": 4.60022,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "AD, MELEE",
    "cast_time": 1.0,
    "cooldown": 25.0,
    "description": "A single target attack that deals 348 physical damage and causes the target to be knocked 2 metres back. This ability has a 3 metre range. Applies Vulnerable to Melee. Susceptible to Anima Deviation.",
    "type": "Active - Elite",
    "weapon": "Shotgun"
  },
  {
    "tree": "Shotgun",
    "name": "Raging Bullet A",
    "scaling": 0.0,
    "scaling_1": 1.21607,
    "scaling_5": 2.40732,
    "note": "<3m"
  },
  {
    "tree": "Shotgun",
    "name": "Raging Bullet B",
    "scaling": 0.0,
    "scaling_1": 1.13665,
    "scaling_5": 2.24948,
    "note": "3-9m"
  },
  {
    "tree": "Shotgun",
    "name": "Raging Bullet C",
    "scaling": 0.0,
    "scaling_1": 1.02249,
    "scaling_5": 2.02513,
    "note": ">9m"
  },
  {
    "tree": "Shotgun",
    "name": "Shotgun Wedding",
    "scaling": 0.86465,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "5x in 2.5s, 25% more dmg per hit (up to 100%), MAGIC",
    "cast_time": 2.5,
    "cooldown": 20.0,
    "description": "Channelled: Every 0.5 seconds for 2.5 seconds. Cone: Affects up to 6 enemies in a 9 metre long 60 degree cone in front of you. A channelled cone attack that deals 66 physical damage per hit. Each time the ability fires and hits any number of targets, the damage of the remaining hits is increased by 25%. This effect can stack up to 4 times. Applies Vulnerable to Magic.",
    "type": "Active - Elite",
    "weapon": "Shotgun"
  },
  {
    "tree": "Shotgun",
    "name": "CQC",
    "scaling": 0.03474,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": ""
  },
  {
    "tree": "Shotgun",
    "name": "Buckshot",
    "scaling": 1.6558,
    "scaling_1": 0.0,
    "scaling_5": 1.81116,
    "note": "1.5s, -0.5 with passive",
    "cast_time": 1.5,
    "cooldown": 10.0,
    "description": "A single target attack that deals 125 physical damage, or 137 physical damage if you have 5 Shotgun resources on the target",
    "type": "Active",
    "weapon": "Shotgun"
  },
  {
    "tree": "Shotgun",
    "name": "Invasive Measures Proc",
    "scaling": 0.27629,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "17.5% chance, hit if full res"
  },
  {
    "tree": "Rifle",
    "name": "Anima Shot",
    "scaling": 0.50628,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Builds 1 Assault Rifle Resource. A single target attack that deals 38 physical damage. You heal your defensive target for 27 and 7.1% of the damage dealt.",
    "type": "Active - Builder",
    "weapon": "Assault Rifle"
  },
  {
    "tree": "Rifle",
    "name": "Fire in the Hole",
    "scaling": 0.0,
    "scaling_1": 0.60952,
    "scaling_5": 1.20813,
    "note": "2 TIMES!!",
    "cast_time": 1.0,
    "cooldown": 4.0,
    "description": "Consumes all Assault Rifle Resources. Sticks a spiked grenade to the target which deals 46 - 91 physical damage and then detonates 2 seconds later dealing 46 - 91 physical damage, based on the number of resources consumed.",
    "type": "Active - Consumer",
    "weapon": "Assault Rifle"
  },
  {
    "tree": "Rifle",
    "name": "Safety Off",
    "scaling": 0.21443,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "3x Burst",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Builds 1 resource for each equipped weapon. A single target Burst attack that hits 3 times, dealing 16 physical damage per hit.",
    "type": "Active - Builder",
    "weapon": "Assault Rifle"
  },
  {
    "tree": "Rifle",
    "name": "Trigger Happy",
    "scaling": 0.64427,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Builds 1 resource for each equipped weapon. A single target attack that deals 49 physical damage. If the target is Hindered, it also becomes Afflicted with a damage over time effect that deals 3 physical damage every second for 5 seconds.",
    "type": "Active - Builder",
    "weapon": "Assault Rifle"
  },
  {
    "tree": "Rifle",
    "name": "Slow the Advance",
    "scaling": 3.67997,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "AD, Hindered",
    "cast_time": 1.0,
    "cooldown": 25.0,
    "description": "GTAoE: Affects up to 6 enemies in a 5 metre radius around the targeted point. A GTAoE that deals 279 physical damage. Affected targets also become Hindered and their movement speed is reduced by 70% for 8 seconds. Also places an area at the targeted point that lasts 8 seconds. Every second it will deal 10 physical damage to up to 6 enemies in a 5 metre radius. Susceptible to Anima Deviation.",
    "type": "Active - Elite",
    "weapon": "Assault Rifle"
  },
  {
    "tree": "Rifle",
    "name": "Slow the Advance Dot",
    "scaling": 0.13104,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "per sec, 8s"
  },
  {
    "tree": "Rifle",
    "name": "Anima Burst",
    "scaling": 0.13997,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "3x Burst",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Builds 1 Assault Rifle Resource. A Burst attack that hits 3 times, dealing 11 physical damage per hit. Heals the defensive target for 35 and 10.1% of the damage dealt.",
    "type": "",
    "weapon": "Assault Rifle"
  },
  {
    "tree": "Rifle",
    "name": "Transfuse Anima",
    "scaling": 0.0,
    "scaling_1": 1.04235,
    "scaling_5": 2.24948,
    "note": "",
    "cast_time": 1.0,
    "cooldown": 4.0,
    "description": "Consumes all Assault Rifle Resources. A single target attack that deals 79 - 170 physical damage, based on the number of resources consumed. Heals the defensive target for 7.1% of the damage dealt. If the target is Hindered, the defensive target also gains a 2% leech effect for 10 seconds.",
    "type": "",
    "weapon": "Assault Rifle"
  },
  {
    "tree": "Rifle",
    "name": "Shellshocker",
    "scaling": 0.86664,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "8x over 2s, AD, Hindered, MELEE",
    "cast_time": 2.0,
    "cooldown": 25.0,
    "description": "Channelled: Every 0.25 seconds for 2 seconds. Column: Affects up to 6 enemies in a 4 metre wide by 12 metre long column in front of you. A channelled column attack that deals 66 physical damage per hit. Affected targets become Hindered and their movement speed is reduced by 70% for 8 seconds. Applies Vulnerable to Melee. Susceptible to Anima Deviation.",
    "type": "Active - Elite",
    "weapon": "Assault Rifle"
  },
  {
    "tree": "Rifle",
    "name": "Three Round Burst",
    "scaling": 0.0,
    "scaling_1": 0.39907,
    "scaling_5": 0.7892,
    "note": "3x burst",
    "cast_time": 1.0,
    "cooldown": 4.0,
    "description": "Consumes all Assault Rifle Resources. A single target Burst attack that hits 3 times, dealing 30 - 60 physical damage per hit, based on the number of resources consumed.",
    "type": "Active - Consumer",
    "weapon": "Assault Rifle"
  },
  {
    "tree": "Rifle",
    "name": "Where it Hurts",
    "scaling": 0.0,
    "scaling_1": 1.19423,
    "scaling_5": 2.40136,
    "note": "afflict -> hindered",
    "cast_time": 1.0,
    "cooldown": 12.0,
    "description": "Consumes all Assault Rifle Resources. A single target attack that deals 90 - 182 physical damage, based on the number of resource consumed. If you hit an Afflicted target, the target becomes Hindered and its movement speed is reduced by 70% for 4 seconds.",
    "type": "Active - Consumer",
    "weapon": "Assault Rifle"
  },
  {
    "tree": "Rifle",
    "name": "Red Mist",
    "scaling": 5.79643,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "2s, MAGIC",
    "cast_time": 2.0,
    "cooldown": 20.0,
    "description": "A single target attack that deals 439 physical damage. This attack cannot be evaded and will not glance. Applies Vulnerable to Magic.",
    "type": "Active - Elite",
    "weapon": "Assault Rifle"
  },
  {
    "tree": "Rifle",
    "name": "Extra Bullet",
    "scaling": 0.09243,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "additional safety off hit",
    "cast_time": 0.0,
    "cooldown": 0.0,
    "description": "\"Safety Off\" performs an additional hit that deals 7 physical damage.",
    "type": "Passive",
    "weapon": "Assault Rifle"
  },
  {
    "tree": "Blade",
    "name": "Delicate Strike",
    "scaling": 0.64427,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Builds 1 resource for each equipped weapon. A single target attack that deals 49 physical damage.",
    "type": "",
    "weapon": "Blade"
  },
  {
    "tree": "Blade",
    "name": "Balanced Blade",
    "scaling": 0.0,
    "scaling_1": 0.59761,
    "scaling_5": 1.1843,
    "note": "",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "PBAoE: Affects up to 6 enemies in a 5 metre radius around you. Consumes all Blade Resources. A PBAoE attack that deals 45 - 90 physical damage, based on the number of resources consumed. Builds 2 Blade Resources if any affected targets are Impaired.",
    "type": "",
    "weapon": "Blade"
  },
  {
    "tree": "Blade",
    "name": "Dancing Blade",
    "scaling": 0.0,
    "scaling_1": 0.54301,
    "scaling_5": 0.81501,
    "note": "5x over 2.5s, Focus",
    "cast_time": 2.5,
    "cooldown": 0.0,
    "description": "Channelled: Every 0.5 seconds for 2.5 seconds. Consumes all Blade Resources. A channelled Focus attack that deals 41 - 62 physical damage per hit, based on the number of resources consumed.",
    "type": "",
    "weapon": "Blade"
  },
  {
    "tree": "Blade",
    "name": "Destiny",
    "scaling": 0.0,
    "scaling_1": 0.73646,
    "scaling_5": 1.9085,
    "note": "",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Consumes all Blade Resources. A single target attack that deals 56 - 145 physical damage, based on the number of resources consumed. If the target is Afflicted, it also applies a damage over time effect that deals 12 physical damage every second for 4 seconds.",
    "type": "",
    "weapon": "Blade"
  },
  {
    "tree": "Blade",
    "name": "Destiny Dot",
    "scaling": 0.1642,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "every sec over 4s"
  },
  {
    "tree": "Blade",
    "name": "Stunning Swirl",
    "scaling": 4.60022,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "RANGED",
    "cast_time": 1.0,
    "cooldown": 25.0,
    "description": "PBAoE: Affects up to 6 enemies in a 5 metre radius around you. A PBAoE attack that deals 348 physical damage. Affected targets also become Impaired and unable to act for 3 seconds. Applies Vulnerable to Ranged.",
    "type": "Active - Elite",
    "weapon": "Blade"
  },
  {
    "tree": "Blade",
    "name": "Grass Cutter",
    "scaling": 0.68001,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Builds 1 resource for each equipped weapon. A single target attack that deals 47 physical damage, or 52 physical damage if the target is Afflicted.",
    "type": "",
    "weapon": "Blade"
  },
  {
    "tree": "Blade",
    "name": "Four Seasons",
    "scaling": 0.58995,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "4x + final over 2.5s, pen, MAGIC",
    "cast_time": 2.5,
    "cooldown": 20.0,
    "description": "Channelled: Every 0.5 seconds for 2.5 seconds. A channelled attack that deals 45 physical damage per hit for the first four hits. The final hit deals 257 physical damage. All hits will penetrate. This ability has a 15 metre range. Applies Vulnerable to Magic.",
    "type": "Active - Elite",
    "weapon": "Blade"
  },
  {
    "tree": "Blade",
    "name": "Four Seasons Final",
    "scaling": 3.39813,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": ""
  },
  {
    "tree": "Blade",
    "name": "Binding Wounds",
    "scaling": 0.0,
    "scaling_1": 1.19621,
    "scaling_5": 2.3686,
    "note": "",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Consumes all Blade Resources. A single target attack that deals 91 - 179 physical damage, based on the number of resources consumed. If the target is Impaired, it becomes Afflicted with a damage over time effect that deals 7 physical damage every seconds for 3 seconds. This ability generates additional hate.",
    "type": "",
    "weapon": "Blade"
  },
  {
    "tree": "Blade",
    "name": "Sling Blade",
    "scaling": 1.23989,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "",
    "cast_time": 1.0,
    "cooldown": 15.0,
    "description": "Throws a blade at the target dealing 94 physical damage and causes the target to become Afflicted with a damage over time effect that deals 6 physical damage every seconds for 5 seconds. Generates a large amount of hate.",
    "type": "",
    "weapon": "Blade"
  },
  {
    "tree": "Blade",
    "name": "Sling Blade Afflict",
    "scaling": 0.07374,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "per sec over 5s"
  },
  {
    "tree": "Blade",
    "name": "The Art of War",
    "scaling": 4.36991,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "lolnope",
    "cast_time": 1.0,
    "cooldown": 35.0,
    "description": "PBAoE: Affects up to 6 enemies in a 5 metre radius around you. A PBAoE attack that deals 331 physical damage and causes each target hit to be forced to attack you for 5 seconds. Targets hit also become Impaired and unable to act for 1 seconds. For each affected target, the next 2 attacks against you will glance, up to a maximum of 10.",
    "type": "Active - Elite",
    "weapon": "Blade"
  },
  {
    "tree": "Blade",
    "name": "Steel Echo",
    "scaling": 0.41396,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "for 10s per hit, FULL HIT",
    "cast_time": 0.0,
    "cooldown": 60.0,
    "description": "You gain a beneficial effect that causes all your Blade attacks for 10 seconds to perform an additional hit dealing 31 physical damage. This additional hit is treated as a full hit. This ability does not trigger and is not affected by global recharge time.",
    "type": "",
    "weapon": "Blade"
  },
  {
    "tree": "Blade",
    "name": "Flight of Daggers",
    "scaling": 0.55195,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "after 5 hits (multihit?)",
    "cast_time": 0.0,
    "cooldown": 0.0,
    "description": "Whenever you hit, you build a Flight of Daggers counter. When the counter reaches 5, you will hit up to 6 enemies in a 5 metre radius around you, dealing 42 physical damage. Affected targets also become Afflicted with a damage over time effect that deals 8 physical damage every second for 5 seconds.",
    "type": "Passive - Elite",
    "weapon": "Blade"
  },
  {
    "tree": "Blade",
    "name": "Sudden Return",
    "scaling": 0.3683,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "on pen",
    "cast_time": 0.0,
    "cooldown": 0.0,
    "description": "Whenever you penetrate, you also perform an additional hit that deals 28 physical damage.",
    "type": "Passive",
    "weapon": "Blade"
  },
  {
    "tree": "Blade",
    "name": "Fortunate Strike",
    "scaling": 0.92024,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "10% per hit",
    "cast_time": 0.0,
    "cooldown": 0.0,
    "description": "Whenever you hit an afflicted target, there is a 10% chance you will perform an additional hit that deals 70 physical damage.",
    "type": "Passive",
    "weapon": "Blade"
  },
  {
    "tree": "Blade",
    "name": "Two Cuts",
    "scaling": 0.136,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": ""
  },
  {
    "tree": "Blade",
    "name": "Finish the Movement",
    "scaling": 0.27629,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "every 2nd focus, hit if full res",
    "cast_time": 0.0,
    "cooldown": 0.0,
    "description": "Whenever you finish channelling a Focus ability, you gain a beneficial effect which causes your next Focus ability to generate 1 resource for your primary weapon. If you already have the maxium available resources when this effect triggers, you will instead perform an additional hit dealing 21 physical damage to the target.",
    "type": "Passive",
    "weapon": "Blade"
  },
  {
    "tree": "Blade",
    "name": "Incision",
    "scaling": 0.13962,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "on pen, per sec, over 3s",
    "cast_time": 0.0,
    "cooldown": 0.0,
    "description": "Whenever you penetrate, you also cause the target to become Afflicted with a damage over time effect that deals 11 physical damage very second for 3 seconds.",
    "type": "Passive",
    "weapon": "Blade"
  },
  {
    "tree": "Hammer",
    "name": "Smash",
    "scaling": 0.64427,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Hammer attack that deals a 54 damage. Builds a weapon resource for each equipped weapon.",
    "type": "Active",
    "weapon": "Hammer"
  },
  {
    "tree": "Hammer",
    "name": "Haymaker",
    "scaling": 0.0,
    "scaling_1": 1.19621,
    "scaling_5": 2.3686,
    "note": "strike",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Hammer strike that deals 119 - 236 damage based on number of resources consumed. If the target is impaired deals 137 - 271. Consumes all hammer resources.",
    "type": "Active",
    "weapon": "Hammer"
  },
  {
    "tree": "Hammer",
    "name": "Shockwave",
    "scaling": 4.60022,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "MAGIC, impair",
    "cast_time": 1.0,
    "cooldown": 25.0,
    "description": "A hammer attack that deals 352 and knocks down enemies in a column in front of you. Targets hit become impaired for 3 seconds. Sets impaired state. Applies Vulnerable to Magic.",
    "type": "Active - Elite",
    "weapon": "Hammer"
  },
  {
    "tree": "Hammer",
    "name": "Grand Slam",
    "scaling": 0.59761,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Hammer attack that deals 50 damage. If the target is weakened deals additional 7 damage AoE, affecting up to 6 enemies in a 5 meter radius. The additional damage generates a large amount of hate. Builds a resource for both weapons.",
    "type": "Active",
    "weapon": "Hammer"
  },
  {
    "tree": "Hammer",
    "name": "Grand Slam Proc",
    "scaling": 0.09232,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": ""
  },
  {
    "tree": "Hammer",
    "name": "Backhanded",
    "scaling": 0.7356,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "build 2 on 0 res",
    "cast_time": 1.0,
    "cooldown": 5.0,
    "description": "Hammer attack that deals 62 damage. Builds two hammer resources if you had none before the attack.",
    "type": "Active",
    "weapon": "Hammer"
  },
  {
    "tree": "Hammer",
    "name": "Molten Steel",
    "scaling": 0.0,
    "scaling_1": 1.14856,
    "scaling_5": 2.2733,
    "note": "15% crit dmg, 30% crit chance",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "A single target attack that deals 114 \u2013 226 damage based on the number of resources consumed. Deals 15% additional critical damage. Consumes all Hammer Resources.",
    "type": "Active",
    "weapon": "Hammer"
  },
  {
    "tree": "Hammer",
    "name": "Bone Breaker",
    "scaling": 0.0,
    "scaling_1": 1.26273,
    "scaling_5": 2.50064,
    "note": "",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "A single target attack that deals 114 - 226 damage, or 126 - 249 if the target is weakened. Damage scales on resources consumed. Consumes all Hammer Resources.",
    "type": "Active",
    "weapon": "Hammer"
  },
  {
    "tree": "Hammer",
    "name": "Eruption",
    "scaling": 4.36991,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "impair, RANGED",
    "cast_time": 1.0,
    "cooldown": 25.0,
    "description": "Hammer attack that deals 334 damage in a column in front of you and knocks enemies into the air for 4 seconds. Sets Impaired state. Applies Vulnerable to Range.",
    "type": "Active - Elite",
    "weapon": "Hammer"
  },
  {
    "tree": "Hammer",
    "name": "Stone's Throw",
    "scaling": 1.51388,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": ""
  },
  {
    "tree": "Hammer",
    "name": "Raging Volcano",
    "scaling": 1.3342,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "5x+ final in 6s",
    "cast_time": 6.0,
    "cooldown": 30.0,
    "description": "A channeled PBAoE attack that deals 102 damage per hit in a 10 meter radius and forces up to 5 nearby enemies to attack you. The last hit will deal 203 damage. While Raging Volcano is channeling, you block all incoming attacks and your movement speed is increase by 30%. Each time this ability hits a target you gain 1 stack of Raging Volcano effect. This effect can stack up to 6 times, lasts 8 seconds and will cause your abilities to deal a additional 30 damage.",
    "type": "Active - Elite",
    "weapon": "Hammer"
  },
  {
    "tree": "Hammer",
    "name": "Raging Volcano Final",
    "scaling": 2.65848,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": ""
  },
  {
    "tree": "Hammer",
    "name": "Raging Volcano Effect",
    "scaling": 0.38616,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "on next non-volc hit"
  },
  {
    "tree": "Hammer",
    "name": "Epicentre",
    "scaling": 0.2656,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "4 stacks, 5s dot"
  },
  {
    "tree": "Hammer",
    "name": "First Blood",
    "scaling": 0.62541,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Hammer Strike that deals 53 damage. Deals 62 damage if you have no Hammer Resources. Builds a weapon resource for each equipped weapon.",
    "type": "Active",
    "weapon": "Hammer"
  },
  {
    "tree": "Hammer",
    "name": "First Blood First",
    "scaling": 0.7356,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": ""
  },
  {
    "tree": "Hammer",
    "name": "Thunderstruck",
    "scaling": 0.55195,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "on crit",
    "cast_time": 0.0,
    "cooldown": 0.0,
    "description": "Increases the duration of Impaired effects you apply by 35%. Whenever you critically hit a Weakened target, you also deal a additional hit for 42 damage.",
    "type": "Passive - Elite",
    "weapon": "Hammer"
  },
  {
    "tree": "Hammer",
    "name": "Tenderising",
    "scaling": 0.09243,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "on weakened hit"
  },
  {
    "tree": "Fist",
    "name": "Claw",
    "scaling": 0.64427,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Builds 1 resource for each equipped weapon. A single target attack that deals 70 physical damage.",
    "type": "Active \u2013 Builder",
    "weapon": "Fist"
  },
  {
    "tree": "Fist",
    "name": "Prey on the Weak",
    "scaling": 0.21443,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "3x burst"
  },
  {
    "tree": "Fist",
    "name": "Go for the Throat",
    "scaling": 2.30011,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "AD, impair",
    "cast_time": 1.0,
    "cooldown": 25.0,
    "description": "A single target attack that deals 250 physical damage. The target also becomes Impaired and unable to activate abilities for 5 seconds and Afflicted with a damage over time that deals 23 physical damage every second for 10 seconds.",
    "type": "Active - Elite",
    "weapon": "Fist"
  },
  {
    "tree": "Fist",
    "name": "Go for the Throat Afflict",
    "scaling": 0.23031,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "10x over 10s"
  },
  {
    "tree": "Fist",
    "name": "Wild at Heart",
    "scaling": 0.0,
    "scaling_1": 1.16842,
    "scaling_5": 2.22367,
    "note": "",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Consumes all Fist resources. A single target attack that deals 95 \u2013 180 physical damage, based on the number of resources. Gives you Feral Regrowth effect, causing your next Fist resource consumer to heal you for 6 \u2013 30.",
    "type": "Active \u2013 Consumer",
    "weapon": "Fist"
  },
  {
    "tree": "Fist",
    "name": "One-Two 1st",
    "scaling": 0.32164,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "Burst"
  },
  {
    "tree": "Fist",
    "name": "One-Two",
    "scaling": 0.0,
    "scaling_1": 0.84678,
    "scaling_5": 1.90104,
    "note": "(passive + 25%)",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Consumes all Fist resources. A Burst attack with two consecutive hits that deals 26 and 69 \u2013 154 physical damage based on the resources consumed. Gives you the Savage Sweep effect, causing the next Fist resource consumer you activate to deal 3 \u2013 14 physical damage in a area around you.",
    "type": "Active \u2013 Consumer",
    "weapon": "Fist"
  },
  {
    "tree": "Fist",
    "name": "Tear Em Up",
    "scaling": 0.0,
    "scaling_1": 1.09794,
    "scaling_5": 2.08965,
    "note": "10% dmg for 4s"
  },
  {
    "tree": "Fist",
    "name": "See Red",
    "scaling": 0.43282,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "20x over 4s, AD, MAGIC, BUG! AD does not work",
    "cast_time": 4.0,
    "cooldown": 25.0,
    "description": "A channeled attack that deals 35 physical damage per hit. While channeling, you are rooted to the ground and your target is unable to activate abilities for 8 seconds. If the root effect ends before the channeling ends, the target takes 333 physical damage.",
    "type": "Active - Elite",
    "weapon": "Fist"
  },
  {
    "tree": "Fist",
    "name": "Gore",
    "scaling": 2.29983,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "RANGED",
    "cast_time": 1.0,
    "cooldown": 20.0,
    "description": "Charge 15 meters to your target. The target must be at least 3 meters away. You charge to your target dealing 186 physical damage to up to 6 enemies in a 5 meter radius and you arrive you gain the minor Evade Chance effect, which increases your chance to evade by 10% for 8 seconds. Affect targets also become afflicted with a damage over time effect that deals 17 physical damage every 0.5 seconds for 5 seconds. The duration of this affliction will be refreshed by hits from any attack, however glancing hits will remove it.",
    "type": "Active - Elite",
    "weapon": "Fist"
  },
  {
    "tree": "Fist",
    "name": "Gore Afflict",
    "scaling": 0.23008,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "2 ticks per sec, refresh on non-glance"
  },
  {
    "tree": "Fist",
    "name": "Fired Up",
    "scaling": 3.26812,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "",
    "cast_time": 1.0,
    "cooldown": 20.0,
    "description": "Heals all group members for 249. Also applies a heal over time effect that heals for 38 every second for 4 seconds.",
    "type": "Active - Elite",
    "weapon": "Fist"
  },
  {
    "tree": "Fist",
    "name": "Inner Spark",
    "scaling": 0.0,
    "scaling_1": 0.10507,
    "scaling_5": 0.21015,
    "note": "with passive",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Consumers all Fist resources. You give your defensive target a reactive heal effect that heals for 7 -13 whenever It is attacked, based on resources consumed. The effect has a duration of 10 seconds.",
    "type": "Active \u2013 Consumer",
    "weapon": "Fist"
  },
  {
    "tree": "Blood",
    "name": "Boiling Blood",
    "scaling": 0.64427,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Builds 1 resource for each equipped weapon. A single target attack that deals 49 magical damage.",
    "type": "",
    "weapon": "Blood"
  },
  {
    "tree": "Blood",
    "name": "Blood Spike",
    "scaling": 1.17338,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "1.5s, 2 res",
    "cast_time": 1.5,
    "cooldown": 0.0,
    "description": "Consumes 2 Blood Resources. Can be powered by your own health. A single target attack that deals 89 magical damage and also causes the target to become Afflicted with a damage over time effect that deals 8 magical damage every 0.5 seconds for 5 seconds. If the target has the Blood Spike damage over time effect already, this ability instead deals 189 magical damage.",
    "type": "",
    "weapon": "Blood"
  },
  {
    "tree": "Blood",
    "name": "Blood Spike Afflict",
    "scaling": 0.10622,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "10x in 5s"
  },
  {
    "tree": "Blood",
    "name": "Blood Spike Hit",
    "scaling": 2.50064,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "if afflicted, instead"
  },
  {
    "tree": "Blood",
    "name": "Cardiac Arrest",
    "scaling": 4.60022,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "AD, impair, MELEE",
    "cast_time": 1.0,
    "cooldown": 25.0,
    "description": "A single target attack that deals 348 magical damage. The target also becomes Impaired and unable to act for 3 seconds. Applies Vulnerable to Melee. Susceptible to Anima Deviation.",
    "type": "Active - Elite",
    "weapon": "Blood"
  },
  {
    "tree": "Blood",
    "name": "Exsanguinate",
    "scaling": 0.81501,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "5x over 2.5s, focus",
    "cast_time": 2.5,
    "cooldown": 0.0,
    "description": "Channelled: Every 0.5 seconds for 2.5 seconds. Consumes 5 Blood Resources. Can be powered by your own health. A channelled Focus attack that deals 62 magical damage per hit. If the target is Impaired, it also becomes Afflicted with a damage over time effect that deals 6 magical damage every second for 10 seconds.",
    "type": "",
    "weapon": "Blood"
  },
  {
    "tree": "Blood",
    "name": "Bloodline",
    "scaling": 0.15486,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "4x, focus",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Channelled: Every 0.25 seconds for 1 second. Builds 1 resource for each equipped weapon. A channelled Focus attack that deals 12 magical damage per hit.",
    "type": "",
    "weapon": "Blood"
  },
  {
    "tree": "Blood",
    "name": "Bloodshot",
    "scaling": 1.72037,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Consumes 2 Blood Resources. Can be powered by your own health. A single target attack that deals 118 magical damage, or 130 magical damage if the target is Afflicted.",
    "type": "",
    "weapon": "Blood"
  },
  {
    "tree": "Blood",
    "name": "Plague",
    "scaling": 0.86465,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "1.5s, 6x over 12s, RANGED",
    "cast_time": 1.5,
    "cooldown": 20.0,
    "description": "A single target attack that causes the target to become Afflicted with a damage over time effect that deals 66 magical damage every 2 seconds for 12 seconds. If the target dies while the Plague damage over time effect is active, enemies within 7 metres will become Afflicted with a new damage over time effect that deals 34 magical damage every 2 seconds for 8 seconds. Applies Vulnerable to Ranged.",
    "type": "Active - Elite",
    "weapon": "Blood"
  },
  {
    "tree": "Blood",
    "name": "Left Hand of Darkness",
    "scaling": 0.45918,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "3res, every sec over 4s",
    "cast_time": 1.0,
    "cooldown": 30.0,
    "description": "Consumes 3 Blood Resources. Can be powered by your own health. Causes the target to become Afflicted with a damage over time effect that deals 35 magical damage every second for 4 seconds. If you hit the target with this ability again while the effect is active, the target becomes Impaired and unable to act for 1 second. This ability will apply a 30 second recharge time when the stun is applied.",
    "type": "",
    "weapon": "Blood"
  },
  {
    "tree": "Blood",
    "name": "Contaminate",
    "scaling": 0.26843,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "1s, every sec over 6s",
    "cast_time": 1.0,
    "cooldown": 40.0,
    "description": "A single target attack that causes the target to become Afflicted by a damage over time effect that deals 20 magical damage every second for 6 seconds. If the target is healed while this damage over time effect is active, it will perfrom a hit on the healer that deals 61 magical damage.",
    "type": "",
    "weapon": "Blood"
  },
  {
    "tree": "Blood",
    "name": "Transfuse and Abuse",
    "scaling": 0.12487,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "every sec over 7s",
    "cast_time": 1.0,
    "cooldown": 20.0,
    "description": "Cleanses up to 3 damage over time effects active on you, and causes the target to become Afflicted with a damage over time effect that deals 9 magical damage every second per effect you cleansed for 7 seconds. This ability can only be activated when you are Afflicted.",
    "type": "",
    "weapon": "Blood"
  },
  {
    "tree": "Blood",
    "name": "Gross Anatomy",
    "scaling": 0.27597,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": ":(",
    "cast_time": 0.0,
    "cooldown": 0.0,
    "description": "Whenever one of your damage over time effects expires or is renewed, it will perform an additional hit that deals 21 magical damage.",
    "type": "Passive - Elite",
    "weapon": "Blood"
  },
  {
    "tree": "Blood",
    "name": "Arterial Pulse",
    "scaling": 0.18365,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "",
    "cast_time": 0.0,
    "cooldown": 0.0,
    "description": "Whenever you penetrate, you perform an additional hit on the target and enemies around it deals 14 magical damage.",
    "type": "Passive",
    "weapon": "Blood"
  },
  {
    "tree": "Blood",
    "name": "Third Degree",
    "scaling": 0.30383,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "per sec over 4s",
    "cast_time": 0.0,
    "cooldown": 0.0,
    "description": "Whenever you penetrate, you build a Third Degree counter. When this counter reaches 3, you also cause the target to become Afflicted with a damage over time effect that deals 23 magical damage every second for 4 seconds.",
    "type": "Passive",
    "weapon": "Blood"
  },
  {
    "tree": "Blood",
    "name": "Torture",
    "scaling": 0.11012,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "hit after focus",
    "cast_time": 0.0,
    "cooldown": 0.0,
    "description": "Whenever you finish channelling a Focus attack, you perform an extra hit that deals 8 magical damage to the target.",
    "type": "Passive",
    "weapon": "Blood"
  },
  {
    "tree": "Chaos",
    "name": "Hand of Change",
    "scaling": 0.64427,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "entropy",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Builds 1 resource for each equipped weapon. A single target attack that deals 49 magical damage.",
    "type": "",
    "weapon": "Chaos"
  },
  {
    "tree": "Chaos",
    "name": "Call for Eris 1st",
    "scaling": 0.92024,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "burst (res x)"
  },
  {
    "tree": "Chaos",
    "name": "Call for Eris",
    "scaling": 0.0,
    "scaling_1": 0.28987,
    "scaling_5": 0.3127,
    "note": "",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Consumes all Chaos Resources. A Burst attack that deals 70 magical damage. Also performs an additional hit per resource consumed, dealing 22 - 24 magical damage per hit. Damage of the additional hits cales based on the number of resources consumed.",
    "type": "",
    "weapon": "Chaos"
  },
  {
    "tree": "Chaos",
    "name": "Schism",
    "scaling": 0.0,
    "scaling_1": 1.11183,
    "scaling_5": 2.20282,
    "note": "",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Consumes all Chaos Resources. A single target attack that deals 84 - 167 magical damage, or 104 - 206 magical damage if the target has below 35% remaining health. Damage scales based on the number of resources consumed.",
    "type": "",
    "weapon": "Chaos"
  },
  {
    "tree": "Chaos",
    "name": "Schism @1 low",
    "scaling": 1.3759,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "<35%"
  },
  {
    "tree": "Chaos",
    "name": "Schism @5 low",
    "scaling": 2.72399,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": ""
  },
  {
    "tree": "Chaos",
    "name": "Domino Effect",
    "scaling": 3.91028,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "",
    "cast_time": 1.0,
    "cooldown": 25.0,
    "description": "PBAoE: Affects up to 6 enemies in up to a 7 metre area around you. A PBAoE attack that damages and pulls affected targets towards you. Affected targets also become Impaired and and knocked to the ground. The range, amount of damage dealt, and impairment duration of this ability are based on the number of targets hit and the range at which they are hit: \u25cb Prompt Critical Event: When only one enemy is within 3 metres this ability deals 348 damage and impairs for 1 second. \u25cb Double-Six Quantum Pieces: When one enemy is within 3 metres and a second is within 5 metres this ability deals 314 damage and impairs for 3 seconds. \u25cb Cascading Boneyard: When at least one enemy is within 3 metres, a second is within 5 metres, and a third is within 7 metres this ability deals 296 damage and impairs for 4 seconds.",
    "type": "Active - Elite",
    "weapon": "Chaos"
  },
  {
    "tree": "Chaos",
    "name": "Paradox",
    "scaling": 1.14956,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "",
    "cast_time": 1.0,
    "cooldown": 10.0,
    "description": "A single target attack that deals 87 magical damage, or 118 magical damage if the target is Impaired.",
    "type": "",
    "weapon": "Chaos"
  },
  {
    "tree": "Chaos",
    "name": "Four Horsemen",
    "scaling": 0.0,
    "scaling_1": 0.27796,
    "scaling_5": 0.4487,
    "note": "4x burst; ??? seems a bit low",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Consumes all Chaos Resources. A single target Burst that hits 4 times, dealing 21 - 34 magical damage per hit, based on the number of resources consumed. Each hit causes the next hit to deal more damage, this bonus stops if a hit glances",
    "type": "",
    "weapon": "Chaos"
  },
  {
    "tree": "Chaos",
    "name": "Pulling the Strings",
    "scaling": 0.0,
    "scaling_1": 1.14956,
    "scaling_5": 2.32195,
    "note": "Minor Hit Chance",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Consumes all Chaos Resources. A single target attack with a 7 metre range that deals 87 - 176 magical damage, based on the number of resources consumed. If the target is Weakened, you gain the Minor Hit Chance effect, which reduces the chance of glancing by 10% for 8 seconds.",
    "type": "",
    "weapon": "Chaos"
  },
  {
    "tree": "Chaos",
    "name": "Prisoner of Fate",
    "scaling": 2.0152,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "5x over 5s, AD, MELEE",
    "cast_time": 5.0,
    "cooldown": 20.0,
    "description": "Channelled: Every second for 5 seconds. A channelled attack that deals 153 magical damage per hit, or 216 magical damage if the target's health is below 35%. This ability has a 7 metre range. Applies Vulnerable to Melee.",
    "type": "Active - Elite",
    "weapon": "Chaos"
  },
  {
    "tree": "Chaos",
    "name": "Prisoner of Fate low",
    "scaling": 2.85702,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": ""
  },
  {
    "tree": "Chaos",
    "name": "Eye of Pandemonium",
    "scaling": 3.67997,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "AD, impair, hindered",
    "cast_time": 1.0,
    "cooldown": 25.0,
    "description": "A single target attack that deals 279 magical damage and causes the target to become Hindered and rooted to the ground for 4 seconds. For the next 10 seconds, up to 6 enemies between 1 and 7 metres of the target will be dealt 14 magical damage each seconds and have a 30% chance to become Impaired as they are knocked into the air. Applies Vulnerable to Ranged. Susceptible to Anima Deviation.",
    "type": "Active - Elite",
    "weapon": "Chaos"
  },
  {
    "tree": "Chaos",
    "name": "Eye of Pandemonium 2ndary",
    "scaling": 0.18365,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "10x over 10s"
  },
  {
    "tree": "Chaos",
    "name": "Run Rampant",
    "scaling": 0.20648,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "3x burst",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Builds 1 resource for each equipped weapon. A single target Burst attack that hits 3 times, dealing 16 physical damage per hit. Gives you a single stack of the Evade Rating effect, which increases your Evade Rating by 40 per stack for 8 seconds. This effect can stack up to 5 times.",
    "type": "",
    "weapon": "Chaos"
  },
  {
    "tree": "Chaos",
    "name": "Suffering and Solace",
    "scaling": 0.0,
    "scaling_1": 1.19621,
    "scaling_5": 2.3686,
    "note": "",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Consumes all Chaos Resources. A single target attack that deals 91 - 179 magical damage, based on the number of resources consumes. If the target is Impaired, you also gain a beneficial effect causing the next 3 hits against you to reflect 3% per resource of the damage dealt back to the attacker.",
    "type": "",
    "weapon": "Chaos"
  },
  {
    "tree": "Chaos",
    "name": "Gravitational Anomaly",
    "scaling": 2.33684,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "3x over 3s, impair",
    "cast_time": 3.0,
    "cooldown": 25.0,
    "description": "Channelled: Every second for 3 seconds. PBAoE: Affects up to 3 random enemies in a 10 metre radius around you. A channelled PBAoE attack that deals 177 magical damage per hit. Affected targets become Impaired and knocked into the air for 2 seconds.",
    "type": "Active - Elite",
    "weapon": "Chaos"
  },
  {
    "tree": "Chaos",
    "name": "Chaotic Pull",
    "scaling": 1.20713,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "",
    "cast_time": 1.0,
    "cooldown": 35.0,
    "description": "A single target attack that deals 91 magical damage and the target becomes Impaired as they are pulled towards you. This ability has 15 metre range.",
    "type": "",
    "weapon": "Chaos"
  },
  {
    "tree": "Chaos",
    "name": "Gnosis",
    "scaling": 0.27895,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "33% on weakened (MULTHIT TEST -> seems to be per hit but at most once per sec)",
    "cast_time": 0.0,
    "cooldown": 0.0,
    "description": "Whenever you hit a Weakened target, there is a 33% chance to perform a additional hit dealing 21 magical damage.",
    "type": "Passive",
    "weapon": "Chaos"
  },
  {
    "tree": "Chaos",
    "name": "From the Abyss",
    "scaling": 0.66214,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "every 3 hits (MULTIHIT TEST -> once per ability)",
    "cast_time": 0.0,
    "cooldown": 0.0,
    "description": "Whenever you hit, you build a From the Abyss counter. When there are 3 counters, you deal 50 magical damage to up to 6 enemies in a 5 metre radius around you, or 65 magical damage to targets that have less than 35% health remaining",
    "type": "Passive - Elite",
    "weapon": "Chaos"
  },
  {
    "tree": "Chaos",
    "name": "Calamity",
    "scaling": 0.47749,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "15% (MULTIHIT TEST!)"
  },
  {
    "tree": "Chaos",
    "name": "Ripple Effect",
    "scaling": 0.11012,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "next attack after 2 burst hits (can be consumed and gained in the same attack)",
    "cast_time": 0.0,
    "cooldown": 0.0,
    "description": "Whenever 2 hits in a row of a Burst attack do no glance, your next attack will perform an additonal hit dealing 8 magical damage.",
    "type": "Passive",
    "weapon": "Chaos"
  },
  {
    "tree": "Chaos",
    "name": "Cutting Thoughts",
    "scaling": 0.18485,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "counter per hit, 5 counter -> next hit does 3x cutting thoughs, gain once per sec",
    "cast_time": 0.0,
    "cooldown": 0.0,
    "description": "Whenever you hit, you build a Cutting Thoughts counter. When there are 5 counters, your next hit performs an additional 3 hits, dealing 14 magical damage per hit. If you perform a glancing hit, the counter will be reset.",
    "type": "Passive",
    "weapon": "Chaos"
  },
  {
    "tree": "Elemental",
    "name": "Shock",
    "scaling": 0.64427,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Builds 1 resource for each equipped weapon. A single target attack that deals 49 magical damage.",
    "type": "",
    "weapon": "Elementalism"
  },
  {
    "tree": "Elemental",
    "name": "Combust",
    "scaling": 2.27926,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "1 res if hindered, 1.5s unless passive",
    "cast_time": 1.5,
    "cooldown": 0.0,
    "description": "Consumes 2 Elemental Resources. A single target attack that deals 173 magical damage. The Elemental Resource cost is reduced by 1 when attacking Hindered targets.",
    "type": "",
    "weapon": "Elementalism"
  },
  {
    "tree": "Elemental",
    "name": "Molten Earth",
    "scaling": 4.60022,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "AD, hindered",
    "cast_time": 1.0,
    "cooldown": 25.0,
    "description": "A single target attack that deals 348 magical damage. The target also becomes Hindered and rooted to the ground for 8 seconds. Susceptible to Anima Deviation.",
    "type": "Active - Elite",
    "weapon": "Elementalism"
  },
  {
    "tree": "Elemental",
    "name": "Thor's Hammer",
    "scaling": 3.39308,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "2s, strike",
    "cast_time": 2.0,
    "cooldown": 0.0,
    "description": "Consumes 5 Elemental Resources. A single target Strike attack that deals 257 magical damage.",
    "type": "",
    "weapon": "Elementalism"
  },
  {
    "tree": "Elemental",
    "name": "Electrical Bolt",
    "scaling": 0.64427,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "2 res if hindered enemy",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Builds 1 resource for each equipped weapon. A single target attack that deals 49 magical damage. If the target is Hindered, this attack generates an additional Elemental Resource.",
    "type": "",
    "weapon": "Elementalism"
  },
  {
    "tree": "Elemental",
    "name": "Flame Strike",
    "scaling": 1.67768,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "2 res, strike",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Consumes 2 Elemental Resources. A single target Strike attack that deals 127 magical damage",
    "type": "",
    "weapon": "Elementalism"
  },
  {
    "tree": "Elemental",
    "name": "Blaze",
    "scaling": 2.6694,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "3 res, 1.5s",
    "cast_time": 1.5,
    "cooldown": 0.0,
    "description": "Consumes 3 Elemental Resources. A single target attack that deals 184 magical damage, or 202 magical damage to Afflicted targets.",
    "type": "",
    "weapon": "Elementalism"
  },
  {
    "tree": "Elemental",
    "name": "Power Line",
    "scaling": 0.18365,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "10x over 10s, RANGED, no procs, vuln immediately, affected by additive"
  },
  {
    "tree": "Elemental",
    "name": "Power Line Detonation",
    "scaling": 2.99004,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "up to x3, realistically only 2.8x"
  },
  {
    "tree": "Elemental",
    "name": "Whiteout",
    "scaling": 0.33156,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "16x over 8s, 1s, does not proc, affected by additive",
    "cast_time": 1.0,
    "cooldown": 25.0,
    "description": "Places an area at the targeted point that lasts 8 seconds. Every 0.5 seconds it will deal 25 magical damage to up to 6 enemies in a 5 metre radius. Targets that are hit 5 times becomes Hindered and rooted to the ground for 4 seconds. Susceptible to Anima Deviation.",
    "type": "Active - Elite",
    "weapon": "Elementalism"
  },
  {
    "tree": "Elemental",
    "name": "Hard Reset",
    "scaling": 4.63695,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "2s, crit, AD",
    "cast_time": 2.0,
    "cooldown": 35.0,
    "description": "A single target attack that deals 351 magical damage and purges all beneficial effects from the target. This attack will always critically hit. Affect targets are unable to act for 1.5 seconds. The target also receives a detrimental effect that purges all beneficial effects every second for 10 seconds. This ability has a 7.5 metre range. Susceptible to Anima Deviation.",
    "type": "Active - Elite",
    "weapon": "Elementalism"
  },
  {
    "tree": "Elemental",
    "name": "Ignition",
    "scaling": 0.64427,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "strike",
    "cast_time": 0.5,
    "cooldown": 0.0,
    "description": "Builds 1 resource for each equipped weapon. A Strike attack that deals 49 magical damage.",
    "type": "",
    "weapon": "Elementalism"
  },
  {
    "tree": "Elemental",
    "name": "Ignite",
    "scaling": 0.61185,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "",
    "cast_time": 1.0,
    "cooldown": 0.0,
    "description": "Builds 1 resource for each equipped weapon. A single target attack that deals 46 magical damage, or 54 magical damage if you have no Elemental Resources.",
    "type": "",
    "weapon": "Elementalism"
  },
  {
    "tree": "Elemental",
    "name": "Ignite First",
    "scaling": 0.70799,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": ""
  },
  {
    "tree": "Elemental",
    "name": "Fire Manifestation",
    "scaling": 0.67107,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "2 res, 1s, 4x over 10s",
    "cast_time": 1.0,
    "cooldown": 10.0,
    "description": "Consumes 2 Elemental Resources. Places a manifestation at the targeted point that lasts 10 seconds. Every 2.5 seconds it will deal 51 magical damage to the closest enemy within a 5 metre radius.",
    "type": "",
    "weapon": "Elementalism"
  },
  {
    "tree": "Elemental",
    "name": "Lightning Manifestation",
    "scaling": 0.16777,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "2 res, 1s, 10x over 10s",
    "cast_time": 1.0,
    "cooldown": 15.0,
    "description": "Consumes 2 Elemental Resources. Places a manifestation at the targeted point that lasts 10 seconds. Every second, it performs a Chain attack that deals 13 magical damage, or 15 magical damage if the target is Hindered.",
    "type": "",
    "weapon": "Elementalism"
  },
  {
    "tree": "Elemental",
    "name": "Overload",
    "scaling": 0.93803,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "2x + final over 3s, MELEE",
    "cast_time": 3.0,
    "cooldown": 20.0,
    "description": "Channelled: Every second for 3 seconds. GTAoE: Affects up to 6 enemies in a 10 metre radius around the targeted point. A channelled GTAoE attack that deals 71 magical damage per hit. Enemies in the area have their movement speed reduced by 30%. The last hit will deal 318 magical damage. Applies Vulnerable to Melee.",
    "type": "Active - Elite",
    "weapon": "Elementalism"
  },
  {
    "tree": "Elemental",
    "name": "Overload final",
    "scaling": 4.2044,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": ""
  },
  {
    "tree": "Elemental",
    "name": "Live Wire Proc",
    "scaling": 1.10389,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "next hit after crit"
  },
  {
    "tree": "Elemental",
    "name": "Elemental Overload",
    "scaling": 0.136,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "33% chance"
  },
  {
    "tree": "Elemental",
    "name": "Mind Over Matter",
    "scaling": 0.11504,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "on crit, every sec over 5s"
  },
  {
    "tree": "Aux",
    "name": "Timber",
    "scaling": 2.99004,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "without augur!",
    "cast_time": 1.0,
    "cooldown": 15.0,
    "description": "A single target attack that deals 226 physical damage.",
    "type": "Active",
    "weapon": "Chainsaw"
  },
  {
    "tree": "Aux",
    "name": "The Carver's Art",
    "scaling": 0.16082,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "15x over 3s",
    "cast_time": 3.0,
    "cooldown": 90.0,
    "description": "A channelled attack that deals 12 physical damage per hit. Both you and the target are rooted to the ground while this ability is active. Channelled: Every 0.2 seconds for 3 second.",
    "type": "Active",
    "weapon": "Chainsaw"
  },
  {
    "tree": "Aux",
    "name": "Scorched Earth",
    "scaling": 0.24962,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": ".5s casttime, 20x over 6s",
    "cast_time": 0.5,
    "cooldown": 25.0,
    "description": "Creates a wall of fire which extends 2 metres forward and 4 metres to either side of the targeted location and lasts 6 seconds. Every 0.3 seconds it will hit up to 6 enemies in the area dealing 19 physical damage.",
    "type": "Active",
    "weapon": "Flamethrower"
  },
  {
    "tree": "Aux",
    "name": "Incendiary Expertise",
    "scaling": 0.11383,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "7x over 7s, +10% each sec (flamethrower passive)"
  },
  {
    "tree": "Anima Deviations",
    "name": "Anima Deviation",
    "scaling": 0.74089,
    "scaling_1": 0.0,
    "scaling_5": 0.0,
    "note": "Averaged"
  }
];
